version: '3'
services:

  sc2infoextractorgo-dev:
    build:
      context: '../'
      dockerfile: './docker/Dockerfile.dev'
    volumes:
      - ..:/app

  sc2infoextractorgo-test:
    build:
      context: '../'
      dockerfile: './docker/Dockerfile.test'
    volumes:
      - ..:/app
    command: [ "go", "test", "./...", "-v" ]
