FROM kaszanas/sc2replaytestdata:latest AS sc2replaytestdata
FROM golang:1.23.3 as build_sc2_info_extractor

# Install rsync for file copying:
RUN apt-get update && apt-get install -y rsync

# Copying test data:
COPY --from=sc2replaytestdata /sc2replaytestdata /test_files/test_replays/

WORKDIR /app

# Copy Golang dependency definitions:
COPY go.mod go.sum /app/

# Get the project dependencies:
RUN --mount=type=cache,target=/go go mod download

COPY . .

# Required for the tests:
ENV WORKSPACE_DIR=/app

# Build the project:
RUN --mount=type=cache,target=/go go build

ENTRYPOINT [ "bash" ]
