version: '3'
services:

  sc2infoextractorgo:
    build:
      context: '../'
      dockerfile: './docker/Dockerfile.dev'
    container_name: sc2infoextractorgo_dev
    volumes:
      - ../logs:/app/logs
      - ../operation_files:/app/operation_files

volumes:
  logs:
