FROM kaszanas/sc2replaytestdata:latest AS sc2replaytestdata
FROM golang:1.21 as build_sc2_info_extractor


WORKDIR /app

# Copying test data:
COPY --from=sc2replaytestdata /sc2replaytestdata /app/test_files/test_replays/

# Copy Golang dependency definitions:
COPY go.mod go.sum /app/

# Get the project dependencies:
RUN --mount=type=cache,target=/go go mod download

COPY . .

# Build the project:
RUN --mount=type=cache,target=/go go build

CMD ["bash"]
