name: continuous integration (ci)

on: [pull_request, workflow_dispatch]

# To successfully find the files that are required for testing:
env:
  TEST_WORKSPACE: ${{ github.workspace }}

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:

      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Build Docker Image With Compose
        run: |
          make action_compose_build

      - name: Run Docker Tests With Compose
        run: |
          make action_compose_test

