name: Continuous Integration (CI)

on: [pull_request, workflow_dispatch]

# To successfully find the files that are required for testing:
env:
  TEST_WORKSPACE: ${{ github.workspace }}

jobs:
  ci:
    # Set up operating system
    runs-on: ubuntu-latest

    # Define job steps
    steps:
      - name: Check-out repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      # Check if the main dockerfile builds:
      - name: Build "Production" Docker Image
        run: |
          make build
        # Check if the main dockerfile builds:
      - name: Build "Development" Docker Image
        run: |
          make build_dev

      # TODO: Running containerized tests:
      # - name: Run Docker Tests With Compose
      #   run: |
      #     make action_compose_test

