name: Docker Build Verification

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - name: Build "Production" Docker Image
        run: make docker_build
      - name: Build "Development" Docker Image Using Compose
        run: make compose_build_dev
