name: Nix Build

on:
  workflow_call:

jobs:
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@3138316df39ed29be04236d7ffc686fa525866aa # v23

      - name: Check flake
        run: nix flake check

      - name: Build package
        run: nix build .#default
