name: Publish Docker image (Release)

on:
  # push:
  #   branches:
  #     - dev
  #     - main
  # workflow_dispatch:
  release:
    types: [published]

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
        # Check if the main dockerfile builds:
      - name: Build "Production" Docker Image
        run: |
          make build

        # Check if the main dockerfile builds:
      - name: Build "Development" Docker Image
        run: |
          make build_dev

  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            kaszanas/sc2infoextractorgo
            ghcr.io/${{ github.repository }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
